# Generated by Django 5.0.3 on 2024-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subTitle', models.TextField()),
                ('heroImage', models.ImageField(upload_to='Hero')),
            ],
        ),
    ]
