# Generated by Django 5.0.3 on 2024-03-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='subTitle',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
