# Generated by Django 5.0.3 on 2024-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0002_alter_heroslider_subtitle_alter_heroslider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Event')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
