# Generated by Django 5.0.3 on 2024-03-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0003_specialevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='Event')),
            ],
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
