# Generated by Django 5.0.3 on 2024-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0005_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('heroImage', models.ImageField(upload_to='Award')),
            ],
        ),
    ]
